// Config -> theme CSS. One call runs the whole pipeline: drivers -> primitives -> Theme Map
// (+ mapping-level overrides) -> CSS, and reports contrast failures for that config.
import { type Context, type DriverInput, withDefaults } from './drivers.ts';
import { resolvePrimitives } from './primitives.ts';
import { themeMap, type ThemeMap } from './themeMap.ts';
import { checkContrast, CONTEXTS } from './contrast.ts';

export interface ThemeConfig {
  /** Driver-level adjustment: a partial override of `defaultDrivers`. */
  drivers?: DriverInput;
  /**
   * Mapping-level adjustment: point a semantic token at a different primitive, per context.
   * Keys are slash names; values are templates, e.g.
   * `{ default: { 'hds/sem/action/color/primary/default/bg': '{hds/prim/color/accent/600}' } }`.
   */
  mapping?: Partial<Record<Context, Record<string, string>>>;
}

const REFS = /\{(hds\/prim\/[^}]+)\}/g;
const SECTION_NAME = /^[a-z0-9-]+$/;

/** `hds/sem/action/color/primary/default/bg` -> `--hds-sem-action-color-primary-default-bg` */
export const cssVar = (slash: string) => `--${slash.replaceAll('/', '-')}`;
const cssValue = (template: string) => template.replace(REFS, (_, name) => `var(${cssVar(name)})`);

export function buildTheme(config: ThemeConfig = {}) {
  const drivers = withDefaults(config.drivers);
  const primitives = resolvePrimitives(drivers);
  const map = themeMap(drivers);

  for (const context of CONTEXTS) {
    for (const [name, value] of Object.entries(config.mapping?.[context] ?? {})) {
      if (!(name in map.default)) throw new Error(`mapping: unknown semantic token "${name}"`);
      map[context][name] = value;
    }
  }
  for (const context of CONTEXTS) {
    for (const [name, value] of Object.entries(map[context])) {
      for (const [, ref] of value.matchAll(REFS)) {
        if (!(ref in primitives)) throw new Error(`${name}: unknown primitive "${ref}"`);
      }
    }
  }

  return {
    drivers,
    primitives,
    map,
    css: toCss(primitives, map, drivers.sections),
    contrast: checkContrast(primitives, map),
  };
}

function toCss(primitives: Record<string, string>, map: ThemeMap, sections: Record<string, Context>): string {
  const selectors = (context: Context) => [
    `[data-context="${context}"]`,
    ...Object.entries(sections)
      .filter(([, ctx]) => ctx === context)
      .map(([name]) => {
        if (!SECTION_NAME.test(name)) throw new Error(`sections: bad section name "${name}"`);
        return `[data-section="${name}"]`;
      }),
  ];
  const block = (sel: string[], entries: [string, string][]) =>
    `  ${sel.join(',\n  ')} {\n${entries.map(([k, v]) => `    ${cssVar(k)}: ${v};`).join('\n')}\n  }`;

  const overridden = Object.keys(map['on-primary']);
  return [
    '/* Generated by handy-ds from a driver config. Do not edit: change the config instead. */',
    '@layer hds.theme, hds.base, hds.components;',
    '@layer hds.theme {',
    block([':root'], [
      ...Object.entries(primitives),
      ...Object.entries(map.default).map(([k, v]): [string, string] => [k, cssValue(v)]),
    ]),
    block(selectors('on-primary'), Object.entries(map['on-primary']).map(([k, v]) => [k, cssValue(v)])),
    // Nested `default` restores the :root value of everything a context can change.
    block(selectors('default'), overridden.map((k) => [k, cssValue(map.default[k])])),
    '}',
    '',
  ].join('\n');
}
